version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    target-branch: "dev/patch"
    directory: "/"
    schedule:
        interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    target-branch: "dev/patch"
    directory: "/"
    schedule:
        interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "gradle"
    target-branch: "dev/patch"
    directory: "/"
    schedule:
        interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
