name: Publish to maven repo

on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: validate gradle wrapper
              uses: gradle/wrapper-validation-action@v2
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'adopt'
                  cache: gradle
            - name: Publish Skript
              run: ./gradlew publish
              env:
                  MAVEN_USERNAME: ${{ secrets.REPO_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.REPO_TOKEN }}
